### ISSUE TITLE
OpenGL Error: 1281 (Invalid Value)

### ISSUE THREAD

**Issue by Robo12324** [ThatFlashCat/BorderlessMinecraft#11]
Whenever I try to use the program on 1.16.2 I get this, and then Minecraft is not borderless window mode. This is also on a LAN server with hamachi, if that might affect it. Any help?

**Comment by ThatFlashCat** [comment]
Hey, sorry for not getting back to you sooner. I'm guessing you fixed the issue, but I'd be curious to know more about what happened in case there is a bug.
