### ISSUE TITLE
Doesn't seem to work as intended on version 1.16.1

### ISSUE THREAD

**Issue by SeikatsuChan** [ThatFlashCat/BorderlessMinecraft#12]
Even after making the window borderless, nothing is able to overlay it (in this case livesplit, despite being set to always be on top and working in other windows)

**Comment by ThatFlashCat** [comment]
That's odd, it's working fine for me on 1.16.3. Can you describe what you're trying to do exactly/provide other details?
![image](https://user-images.githubusercontent.com/26885142/95367462-6bb5e280-089a-11eb-9eb6-23729bdbecb2.png)

**Comment by SeikatsuChan** [comment]
Simply trying to run the game in borderless windowed with livesplit on top; I've managed to get it working using your old tutorial and windows explorer (https://www.youtube.com/watch?v=xuyPuOLviNo)

Not sure what else to add that's productive, despite that I'm running it with Fabric/Sodium. It just doesn't allow the window to be overlayed by other windows.

**Comment by GramBezEndu** [comment]
After setting "Fullscreen: OFF" in my game I was able to go borderless without any problems. When I tried to do the same with "Fullscreen: ON" it did not work.

Tested on 1.16.1 also, no mods.

**Comment by ThatFlashCat** [comment]
This is expected behavior. When in fullscreen mode, the game isn't technically a window and the utility isn't able to make it borderless. @GramBezEndu

**Comment by ThatFlashCat** [comment]
Closed due to inactivity.
