### ISSUE TITLE
Not Working on AMD graphics

### ISSUE THREAD

**Issue by Hartulino** [ThatFlashCat/BorderlessMinecraft#17]
Hello, I have been trying to fix this problem for a long time. I am a Minecraft Speedruner and I need livesplits above the game. Everytime I asked someone if it works for them they said yes. But I realised that I have AMD GPU and all the others have Nvidia. So my friend with AMD GPU tried it and it didn't work for em either. Do you know how to solve this? Thx

**Comment by ThatFlashCat** [comment]
Can you send a screenshot of what happens? @Hartulino 

Sorry for the late reply, Github refuses to notify me of new issues. :(

**Comment by Hartulino** [comment]
![2021-02-24_10 27 16](https://user-images.githubusercontent.com/69189611/108979823-57c51e80-768b-11eb-8d62-0ff1ae0b774e.png)
![Bez názvu](https://user-images.githubusercontent.com/69189611/108979833-5ac00f00-768b-11eb-9982-640995f128df.png)
So when I click on it it just doesn't work

**Comment by ThatFlashCat** [comment]
So nothing happens when you click "Singleplayer?"

**Comment by Hartulino** [comment]
When I click on anything in the game, the game overlays the livesplit

**Comment by ThatFlashCat** [comment]
Isn't that expected? The Minecraft window is probably overlapping livesplit.

**Comment by Hartulino** [comment]
No, I want the livesplit to overlay minecraft and idk how to do that. It works for everyone with Nvidia graphics.

**Comment by Seangles** [comment]
> No, I want the livesplit to overlay minecraft and idk how to do that. It works for everyone with Nvidia graphics.

Yes, it's absolutely the same for me. It even glitches out to a black screen for a split second when I switch focus to Minecraft (kinda like in fullscreen), which never happens in regular windowed mode. And Livesplit is always over Minecraft in windowed but not in borderless (even when the focus is on Minecraft). Also in borderless Minecraft won't minimize how hard I try. I have AMD Radeon RX 580 (with Ryzen CPU) and my monitor is connected by displayport cable if this helps.
Maybe there are some AMD settings which may cause the issue?

**Comment by ThatFlashCat** [comment]
Hmm, maybe the way I remove the window border breaks livesplit.

> Also in borderless Minecraft won't minimize how hard I try.

Well, the minimize button has been removed. I could probably add it to the UI and let you minimize/restore the window that way.
