### ISSUE TITLE
Nothing listed under the session selection window

### ISSUE THREAD

**Issue by SekkeyWho** [ThatFlashCat/BorderlessMinecraft#2]
I open the program, Minecraft is running, yet in the window where I am supposed to select my Minecraft session to make it borderless, nothing appears.

**Comment by ThatFlashCat** [comment]
Is "Minecraft" at the beginning of the window title?

**Comment by SekkeyWho** [comment]
Yes, when the game is running the window is titled just "Minecraft", but nothing appears under the session selection window in your software.

**Comment by ThatFlashCat** [comment]
Are you by any chance running the Windows 10 Edition of Minecraft?
