### ISSUE TITLE
No clear indication what file starts up the program

### ISSUE THREAD

**Issue by DarreMo** [ThatFlashCat/BorderlessMinecraft#3]
Hey,

I was trying to figure out what file starts up the program but every file I click gives me a prompt to chose with what program I want to open .config formatted files. No file seems to be a file to actually start the program up.

Now I am just wondering if I am just blind and cannot find it

**Comment by ThatFlashCat** [comment]
Sorry for the incredibly late reply, I have no idea why but github sends no notifications whatsoever about these issues. You'll need to run the .exe file from the release download.
