### ISSUE TITLE
Doesn't work on Modpacks.

### ISSUE THREAD

**Issue by Virtualexis** [ThatFlashCat/BorderlessMinecraft#4]
Hey ! Wanted to use your software , but because you probably make this works with the windows name , and not the process name , it does not work due to the name of the window being different on  modpacks instances

**Comment by ThatFlashCat** [comment]
Sorry for not replying to this, for whatever reason I don't get notifications about issues. I use a combination of window and process name, as the process is the generic javaw.exe. I'd need a list of common client titles to match from.
