### ISSUE TITLE
Works only on primary monitor.

### ISSUE THREAD

**Issue by z4ha** [ThatFlashCat/BorderlessMinecraft#6]
Is there a way to select monitors? I would love to have the option to setup at secondary monitor. Love this app!

**Comment by ThatFlashCat** [comment]
You could do it by enabling advanced mode and manually setting the X position. For a 1080p monitor it would be -1920 or 1920, depending on which side of the main monitor you want it on. Adding it as a regular feature is something I may add in the future, though. @z4ha
