### ISSUE TITLE
Custom title appends to the existing title.

### ISSUE THREAD

**Issue by ThePizzaMuncher** [ThatFlashCat/BorderlessMinecraft#8]
I am a total moron, ignore this. I would like to know if it's possible to have the option to replace the title instead of append to it, the way it used to.

If I try to set a custom title to a Minecraft window, it appends the title I try to give it to the existing title. This stacks, meaning I just get a longer and longer title as I try to give it a custom title.

Here's the standard title:
![image](https://user-images.githubusercontent.com/60735922/80037815-a0083300-84f4-11ea-94a3-1c33b27e3490.png)

first attempt
![image](https://user-images.githubusercontent.com/60735922/80037868-badaa780-84f4-11ea-9fbc-d32609887880.png)

second attempt
![image](https://user-images.githubusercontent.com/60735922/80037909-d47bef00-84f4-11ea-864b-6617369fccdd.png)

Third for good measure
![image](https://user-images.githubusercontent.com/60735922/80038007-fd03e900-84f4-11ea-97c7-5f04dd7a9ad6.png)

**Comment by ThatFlashCat** [comment]
I will look into this when I have the time. By default the new title is appended to the existing which is confusing. I will look into a better way of doing window detection.

**Comment by ThatFlashCat** [comment]
I have addressed this issue in the latest release. @ThePizzaMuncher

**Comment by ThePizzaMuncher** [comment]
Thank you :)
